name: Test ESP bool parser

on:
  pull_request:
  push:
    branches:
      - main

env:
  IDF_PATH: /opt/esp/idf

defaults:
  run:
    shell: bash

jobs:
  build-python-packages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v5
        with:
          python-version: "3.7"
      - run: |
          pip install -U pip
          pip install flit
          flit build
      - name: Upload built python packages
        uses: actions/upload-artifact@v6
        with:
          name: wheel
          path: dist/esp_bool_parser-*.whl

  basic-test:
    needs: build-python-packages
    runs-on: ubuntu-22.04
    env:
      FLIT_ROOT_INSTALL: 1

    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.7"
            pyparsing: "==2.4"
            slug: "py37-pp24"
          - python-version: "3.14"
            pyparsing: ">=3"
            slug: "py314-pplatest"
          - python-version: "3.14"
            pyparsing: "==3.0.9"
            slug: "py314-pp309"

    name: Test (Python ${{ matrix.python-version }}, pyparsing ${{ matrix.pyparsing }})

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install dependencies
        run: |
          pip install flit pyparsing${{ matrix.pyparsing }}

      - name: Install package
        run: flit install -s

      - name: Run tests
        run: |
          pip show pyparsing
          python --version

          pytest \
            --cov esp_bool_parser \
            --cov-report term-missing:skip-covered \
            --junit-xml pytest-${{ matrix.slug }}.xml \
            | tee pytest-coverage-${{ matrix.slug }}.txt

      - name: Save PR number
        if: github.event_name == 'pull_request'
        run: echo ${{ github.event.number }} > pr_number.txt

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.slug }}
          path: |
            pr_number.txt
            pytest-coverage-${{ matrix.slug }}.txt
            pytest-${{ matrix.slug }}.xml
          retention-days: 1
